apiVersion: v1
kind: Service
metadata:
  name: mypod-service
spec:
  selector:
    app: mypod
  ports:
    - protocol: TCP
      port: 80        # External port exposed to clients
      targetPort: 8000 # The internal port your container is using
  type: NodePort